enum Names {
  Character = "Character",
  Archer = "Archer",
  Champion = "Champion",
  Spearman = "Spearman",
  Archangel = "Archangel",
  BlackKnight = "Black Knight",
  BoneDragon = "Bone Dragon",
  Crusader = "Crusader",
  EnergyElemental = "Energy Elemental",
  Griffin = "Griffin",
  IceElemental = "Ice Elemental",
  Lich = "Lich",
  MagicElemental = "Magic Elemental",
  MagmaElemental = "Magma Elemental",
  Phoenix = "Phoenix",
  Skeleton = "Skeleton",
  StormElemental = "Storm Elemental",
  Vampire = "Vampire",
  Wrath = "Wrath",
  Zealot = "Zealot",
  Zombie = "Zombie",
  Fairy = "Fairy",
}
export default Names;
