enum Names {
    Character,
    Archer,
    Champion,
    Spearman,
    Archangel,
    BlackKnight,
    BoneDragon,
    Crusader,
    EnergyElemental,
    Griffin,
    IceElemental,
    Lich,
    MagicElemental,
    MagmaElemental,
    Phoenix,
    Skeleton,
    StormElemental,
    Vampire,
    Wrath,
    Zealot,
    Zombie,
    Fairy,
}
export default Names